export const female = [
  {
    ID: "1",
    image_path: "female1.png",
    title: "Brushed Bomber",
    category: "Jackets",
    price: "225",
  },
  {
    ID: "2",
    image_path: "female2.png",
    title: "Lite Sweatpants",
    category: "Pants",
    price: "150",
  },
  {
    ID: "3",
    image_path: "female3.png",
    title: "Brushed Raglan Sweatshirt",
    category: "Sweater",
    price: "195",
  },
  {
    ID: "4",
    image_path: "female4.png",
    title: "Flex Sweatshirt",
    category: "Sweater",
    price: "175",
  },
  {
    ID: "5",
    image_path: "female5.png",
    title: "Imperial Alpaca Hoodie",
    category: "Jackets",
    price: "525",
  },
  {
    ID: "6",
    image_path: "female6.png",
    title: "Pink Fleece Sweatpants",
    category: "Pants",
    price: "195",
  },
  {
    ID: "7",
    image_path: "female7.png",
    title: "Muscle Tank",
    category: "T Shirts",
    price: "75",
  },
  {
    ID: "8",
    image_path: "female8.png",
    title: "Flex Sweatpants",
    category: "Pants",
    price: "175",
  },
  {
    ID: "9",
    image_path: "female9.png",
    title: "Cameryn Sash Tie Dress",
    category: "Dress",
    price: "547",
  },
];
